# Packages

In [14]:
import torch
import numpy as np

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [4]:
t3 = torch.tensor([
    [5., 6],
    [7, 8],
    [9,10]
])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [5]:
t4 = torch.tensor([
    [
        [11., 12., 13.],
        [13., 14., 15.]
    ],

    [
        [15., 16., 17.],
        [17., 18., 19.]
    ]
])

t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [9]:
print(t1, t1.shape)
print(t2, t2.shape)
print(t3, t3.shape)
print(t4, t4.shape)

tensor(4.) torch.Size([])
tensor([1., 2., 3., 4.]) torch.Size([4])
tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) torch.Size([3, 2])
tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]]) torch.Size([2, 2, 3])


# Tensor operations and gradients

In [10]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [11]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [12]:
y.backward()

In [13]:
print("dy/dx: ", x.grad)
print(f"dy/dw: {w.grad}")
print("dy/db: {}".format(b.grad))

dy/dx:  None
dy/dw: 3.0
dy/db: 1.0


# Interoperability between pytorch and numpy

In [15]:
x = np.array([
    [1,2],
    [3,4]
])
x

array([[1, 2],
       [3, 4]])

In [16]:
x.shape

(2, 2)

In [17]:
y = torch.from_numpy(x)
type(y)

torch.Tensor

In [18]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [19]:
# convert torch to numpy array
z = y.numpy()
z

array([[1, 2],
       [3, 4]])